---
ID: "7e5fa35e-3589-4938-814a-24f15cd1e6a9"
Parent: "a6dff70c-5e6f-4515-b552-a96dac72c76a"
Template: "a87a00b1-e6db-45ab-8b54-636fec3b5523"
Path: /sitecore/content/Challenger/Challenger/Settings/ComponentsSettings
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20231129T081715Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\yrandri@challenger.com.au
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\yrandri@challenger.com.au
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "880ca32b-18eb-47b8-927f-82b0e9cde195"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\yrandri@challenger.com.au
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231129T081715Z
