import { ComponentMap } from '@sitecore-content-sdk/nextjs';
import { componentMap as generated } from 'temp/componentBuilder';

// AUTO-GENERATED by fix-content-sdk.ps1 - DO NOT EDIT BY HAND.

export const componentMap: ComponentMap = new Map(generated);

export default componentMap;
