"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.getComponentBuilderTemplate = void 0;
const isLazyLoadingModule = (componentPath) => componentPath.includes('.dynamic');
const removeDynamicModuleNameEnding = (moduleName) => moduleName.replace(/\.?dynamic$/i, '');
/**
 * Generate component builder template
 * @param {(PackageDefinition | ComponentFile)[]} components components to include in component builder
 * @returns generated component builder template
 */
const getComponentBuilderTemplate = (components) => {
    const componentFiles = components.filter((component) => component.componentName && (component.importPath != null && !component.importPath.includes('_tests_') && !component.componentName.includes('.stories')));
    
    const packages = components.filter((component) => component.components);
    const hasLazyModules = componentFiles.find((component) => isLazyLoadingModule(component.importPath));

    return `/* eslint-disable */
// Do not edit this file, it is auto-generated at build time!
// See scripts/generate-component-builder/index.ts to modify the generation of this file.

${hasLazyModules ? "import dynamic from 'next/dynamic';" : ''}
import { ComponentMap } from '@sitecore-content-sdk/nextjs';

${packages
        .map((pkg) => {
        const list = pkg.components.map((c) => c.moduleName).join(', ');
        return `import { ${list} } from '${pkg.name}';\n`;
    })
        .join('')}
${componentFiles
        .map((component) => {
        if (isLazyLoadingModule(component.importPath)) {
            const moduleName = removeDynamicModuleNameEnding(component.moduleName);
            return `const ${moduleName} = {
  module: () => import('${component.importPath}'),
  element: (isEditing?: boolean) => isEditing ? require('${component.importPath}')?.default : dynamic(${moduleName}.module)
}`;
        }
        return `import * as ${component.moduleName} from '${component.importPath}';`;
    })
        .join('\n')}

const components: ComponentMap = new Map();
${packages
        .map((p) => p.components.map((component) => `components.set('${component.componentName}', ${component.moduleName});\n`))
        .flat()
        .join('')}
${componentFiles
        .map((component) => 
                `components.set('${isLazyLoadingModule(component.importPath)
                    ? removeDynamicModuleNameEnding(component.componentName)
                    : component.componentName}', ${isLazyLoadingModule(component.importPath)
                    ? removeDynamicModuleNameEnding(component.moduleName)
                    : component.moduleName});`
        )
        .join('\n')}

export const componentMap = components;
`;
};
exports.getComponentBuilderTemplate = getComponentBuilderTemplate;
