import fs from 'fs';
import path from 'path';
import { constantCase } from 'constant-case';
import { JssConfig } from 'lib/config';
import { jssConfigFactory } from './config';
import scConfig from 'sitecore.config';

/*
  CONFIG GENERATION
  Generates the /src/temp/config.js file which contains runtime configuration
  that the app can import and use.
*/
const defaultConfig: JssConfig = {
  sitecoreApiKey: scConfig.sitecoreApiKey,
  sitecoreApiHost: scConfig.sitecoreApiHost,
  sitecoreMediaHost: scConfig.sitecoreMediaHost,
  sitecoreSiteName: scConfig.sitecoreSiteName,
  graphQLEndpointPath: scConfig.graphQLEndpointPath,
  defaultLanguage: scConfig.defaultLanguage,
  graphQLEndpoint: scConfig.graphQLEndpoint,
  layoutServiceConfigurationName: scConfig.layoutServiceConfigurationName,
  publicUrl: scConfig.publicUrl,
};

generateConfig(defaultConfig);

function generateConfig(defaultConfig: JssConfig): void {
  jssConfigFactory
    .create(defaultConfig)
    .then((config) => {
      writeConfig(config);
    })
    .catch((e) => {
      console.error('Error generating config');
      console.error(e);
      process.exit(1);
    });
}

function writeConfig(config: JssConfig): void {
  let configText = `/* eslint-disable */
// Do not edit this file, it is auto-generated at build time!
// See scripts/bootstrap.ts to modify the generation of this file.
const config = {};\n`;

  Object.keys(config).forEach((prop) => {
    configText += `config.${prop} = process.env.${constantCase(prop)} || '${config[prop] ?? ''}',\n`;
  });

  configText += `module.exports = config;`;

  const configPath = path.resolve('src/temp/config.js');
  console.log(`Writing runtime config to ${configPath}`);
  fs.writeFileSync(configPath, configText, { encoding: 'utf8' });
}
