import { IconGroup } from './icon.types';

export const iconList: IconGroup[] = [
  {
    name: 'Utility',
    icons: [
      'SearchIcon',
      'UserIcon',
      'ChevronDownIcon',
      'ChevronUpIcon',
      'ChevronLeftIcon',
      'ChevronRightIcon',
      'ArrowDownIcon',
      'ArrowUpIcon',
      'ArrowLeftIcon',
      'ArrowRightIcon',
      'CloseIcon',
      'CheckIcon',
      'EyeOpenIcon',
      'EyeHideIcon',
      'CalendarIcon',
      'TimerIcon',
      'ExternalLinkIcon',
      'DownloadIcon',
      'ContentIcon',
      'PlayIcon',
    ],
  },
  {
    name: 'General',
    icons: [
      'CoinIcon',
      'ChartBarIcon',
      'ChartPieIcon',
      'CommentIcon',
      'ConnectIcon',
      'ChatIcon',
      'CogIcon',
      'DatabaseIcon',
      'EyeIcon',
      'GlassesIcon',
      'GlobeIcon',
      'UmbrellaIcon',
      'SuitcaseIcon',
      'PlaneIcon',
      'PersonIcon',
      'HomeIcon',
      'LightIcon',
      'LockIcon',
      'MailIcon',
      'MapMarkerIcon',
      'MapIcon',
      'PhoneIcon',
      'ApplyIcon',
      'NoteIcon',
      'SearchUserIcon',
      'SearchListIcon',
      'UserFilledIcon',
      'PuzzleIcon',
      'BoxCheckIcon',
    ],
  },
  {
    name: 'Social',
    icons: ['FacebookIcon', 'XIcon', 'TwitterIcon', 'InstagramIcon', 'LinkedInIcon', 'YoutubeIcon'],
  },
];
